title: LEAD Madrid Living Lab open data
description: This dataset is a monthly-updated list of all services, route optimization and environmental KPIs data generated in the project.

publisher_text: Last Mile Team
publisher_url: https://www.lastmile.team

license_text: UK Open Government Licence (OGL)
license_url: http://reference.data.gov.uk/id/open-government-licence

frequency: Monthly

certificate_embed: <script src='https://certificates.theodi.org/datasets/2502/certificates/14842/badge.js'></script>
